version: "3.3"
services:
    zoo:
        image: debezium/zookeeper
        ports:
         - "2181:2181"
         - "2888:2888"
         - "3888:3888"    
    kafka:
        image: debezium/kafka
        ports:      
         - "9092:9092"      
        links:
          - zoo
        environment:
        - ZOOKEEPER_CONNECT=zoo:2181
    connect:
        image: debezium/connect
        ports:
         - 8083:8083
         - 5005:5005
        links:
          - kafka
        environment:
         - BOOTSTRAP_SERVERS=kafka:9092
         - GROUP_ID=1
         - CONFIG_STORAGE_TOPIC=my_connect_configs
         - OFFSET_STORAGE_TOPIC=my_connect_offsets
         - STATUS_STORAGE_TOPIC=my_connect_statuses
         - LD_LIBRARY_PATH=/instant_client
         - KAFKA_DEBUG=true
         - DEBUG_SUSPEND_FLAG=n
         - JAVA_DEBUG_PORT=0.0.0.0:5005
    debui: 
        image: debezium/debezium-ui
        ports: 
         - 8080:8080
        links:
         - connect
        environment: 
         - KAFKA_CONNECT_URIS=http://connect:8083